# AEDecode-Patient1023-LocalEP.rq
# 
# 
PREFIX cdiscpilot01: <https://w3id.org/phuse/cdiscpilot01#>
PREFIX code: <https://w3id.org/phuse/code#>
PREFIX meddra: <https://w3id.org/phuse/meddra#>
PREFIX skos: <http://www.w3.org/2004/02/skos/core#>
PREFIX study: <https://w3id.org/phuse/study#>

SELECT * 
WHERE{
  # SERVICE <http://34.216.170.22:5820/CTDasRDFOnt/query>
  SERVICE <db://CTDasRDFOnt>
  {
  #  {
      cdiscpilot01:Person_01-701-1023  study:afflictedBy ?aeiri .
      ?aeiri code:hasCode ?lltiri .
  #  }
  }

  # SERVICE <http://34.216.170.22:5820/MedDRA211/query>
  SERVICE <db://MedDRA>
  { 
     {
      ?lltiri  <https://w3id.org/phuse/meddra#hasPT> ?o .
      #meddra:hasPT   ?ptiri ;
       #        skos:prefLabel ?LLT .
     }
  }
}
 # }              
#  }#
#}               
##      OPTIONAL
##      {
##        ?ptiri   meddra:hasHLT  ?hltiri ;
##                 skos:prefLabel ?pt .
##      }
##      OPTIONAL
##      {
##        ?hltiri  meddra:hasHLGT ?hlgtiri ;
##                 skos:prefLabel ?HLT .
##      }
##      OPTIONAL
##      {
##        ?hlgtiri meddra:hasSOC  ?sociri ;
##                 skos:prefLabel ?HLGT .
##      }
##      OPTIONAL
##      {
##        ?sociri  skos:prefLabel ?SOC .
##      }  
##    }
##  }
#}